# Generated by Django 5.1.2 on 2024-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='device_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='redmine_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
