# Generated by Django 5.1.2 on 2024-11-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_device_id_alter_employee_redmine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
