# Generated by Django 5.1.2 on 2024-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, choices=[('BP', 'Bottle Payments'), ('DS', 'Designer'), ('DV', 'Developer'), ('MR', 'Manager'), ('OA', 'Office Admin'), ('QA', 'Quality Assurance')], max_length=3, null=True),
        ),
    ]
