# Generated by Django 5.1.2 on 2024-11-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
    ]
