# Generated by Django 5.1.2 on 2024-11-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='designation',
        ),
    ]
