# Generated by Django 5.1.2 on 2024-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('record_time', models.DateTimeField(null=True)),
                ('login_type', models.CharField(choices=[('RM', 'Remote'), ('OS', 'On-Site'), ('HR', 'Hybrid')], max_length=2)),
                ('work_hour', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

